# Kitty terminal theme
# https://sw.kovidgoyal.net/kitty/conf/#color-scheme

background              #{{bg0}}
foreground              #{{fg1}}
selection_background    #{{bg3}}
selection_foreground    #{{fg0}}
cursor                  #{{fg1}}
cursor_text_color       #{{bg0}}
url_color               #{{blue}}

# Tabs
active_tab_background   #{{bg0}}
active_tab_foreground   #{{fg0}}
inactive_tab_background #{{bg2}}
inactive_tab_foreground #{{fg3}}
tab_bar_background      #{{bg1}}

# Marks
mark1_background        #{{bg3}}
mark1_foreground        #{{fg0}}
mark2_background        #{{purple}}
mark2_foreground        #{{bg0}}
mark3_background        #{{cyan}}
mark3_foreground        #{{bg0}}

# Black
color0  #{{bg0}}
color8  #{{bg4}}

# Red
color1  #{{red}}
color9  #{{red}}

# Green
color2  #{{green}}
color10 #{{green}}

# Yellow
color3  #{{yellow}}
color11 #{{yellow}}

# Blue
color4  #{{blue}}
color12 #{{blue}}

# Magenta / Purple
color5  #{{purple}}
color13 #{{pink}}

# Cyan
color6  #{{cyan}}
color14 #{{cyan}}

# White
color7  #{{fg1}}
color15 #{{fg0}}
