-- This file is autogenerated (edit palettes/black.ini to change)
return {
  bg0     = "#000000",
  bg1     = "#1f2335",
  bg2     = "#24283b",
  bg3     = "#292e42",
  bg4     = "#3b4261",

  fg0     = "#e0def4",
  fg1     = "#e0def4",
  fg2     = "#908caa",
  fg3     = "#6e6a86",

  red     = "#eb6f92",
  orange  = "#ea9a97",
  yellow  = "#f6c177",
  green   = "#9ccfd8",
  cyan    = "#9ccfd8",
  blue    = "#3e8fb0",
  purple  = "#c4a7e7",
  pink    = "#eb6f92",

  err     = "#eb6f92",
  warn    = "#f6c177",
  info    = "#9ccfd8",
  hint    = "#3e8fb0",
  added   = "#9ccfd8",
  changed = "#f6c177",
  removed = "#eb6f92",

  none    = "NONE",
}
